# Generated by Django 4.2.13 on 2024-07-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpage", name="url", field=models.URLField(),
        ),
    ]
